dist: trusty
sudo: required
language: go
services:
  - docker
go:
  - "1.10.x"
env:
  - DB=mysql PORT=3005
  - DB=mysql PORT=3008
  - DB=mariadb PORT=3010

before_script:
  - docker-compose pull
  - docker-compose build
  - docker-compose up
  - test "${DB}" = "mysql" && (mysql -P $PORT -u root -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';") || echo "No MySQL"
  - echo 'SELECT VERSION()' | mysql -uroot -P $PORT

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT=localhost:$PORT
  - export MYSQL_PASSWORD=
  - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
