dist: trusty
sudo: required
language: go
services:
  - docker
go:
  - "1.10.x"

before_script:
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  - sleep 20
  - mysql -h127.0.0.1 -P3305 -uroot -ptests -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - mysql -h127.0.0.1 -P3308 -uroot -ptests -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - mysql -h127.0.0.1 -P3310 -uroot -ptests -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - echo 'SELECT VERSION()' | mysql -uroot -ptests -h127.0.0.1 -P3305
  - echo 'SELECT VERSION()' | mysql -uroot -ptests -h127.0.0.1 -P3308
  - echo 'SELECT VERSION()' | mysql -uroot -ptests -h127.0.0.1 -P3310

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - MYSQL_USERNAME=root MYSQL_ENDPOINT=127.0.0.1:3305 MYSQL_PASSWORD=tests make testacc
  - MYSQL_USERNAME=root MYSQL_ENDPOINT=127.0.0.1:3308 MYSQL_PASSWORD=tests make testacc
  - MYSQL_USERNAME=root MYSQL_ENDPOINT=127.0.0.1:3310 MYSQL_PASSWORD=tests make testacc

after_script:
  - docker-compose down

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
