dist: trusty
sudo: required
language: go
services:
  - docker
go:
  - "1.10.x"
env:
  - DB=mysql VERSION=5 PORT=3005
  - DB=mysql VERSION=8 PORT=3008
  - DB=mariadb VERSION=10 PORT=3010

before_script:
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  - sleep 20
  - test "${DB}" = "mysql" && (mysql -P $PORT -u root -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';") || echo "No MySQL"
  - export DOCKER_IP=$(docker-machine ip "${DB}${VERSION}")
  - echo 'SELECT VERSION()' | mysql -uroot -h${DOCKER_IP} -P $PORT

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT=${DOCKER_IP}:${PORT}
  - export MYSQL_PASSWORD=tests
  - make testacc

after_script:
  - docker-compose down

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
