dist: trusty
sudo: required
language: go
services:
  - docker
go:
  - "1.10.x"
env:
  - DB=mysql
  - DB=mariadb
addons:
  apt:
    sources:
      - mariadb-10.0

before_script:
  - sudo apt-get update
  - test "${DB}" = "mariadb" && (sudo service mysql stop && sudo apt-get install mariadb-server mariadb-client libmariadbclient-dev) || echo "No MariaDB"
  - sudo service mysql restart
  - test "${DB}" = "mysql" && mysql -u root -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';" || echo "No MySQL"

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT=localhost:3306
  - export MYSQL_PASSWORD=
  - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
